version: '3.8'

services:
  app:
    build: .
    ports:
      - "8218:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PASS=${DB_PASSWORD} # fallback
      - DB_NAME=${DB_NAME}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

